#
#kafka.consumer.id=consumerServer
#kafka.producer.id=producerServer
#kafka.server=localhost:9092
#kafka.group.id=server.broadcast

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
#    username: admin
#


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@sql.edu-netcracker.com:1251:XE
    username: TLT_5
    password: TLT_5


#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver#    password: admin
#                         url: jdbc:oracle:thin:@sql.edu-netcracker.com:1251:XE
#                         username: TLT_5
#                         password: TLT_5

#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@sql.edu-netcracker.com:1251:XE
#spring.datasource.username= TLT_5
#spring.datasource.password= TLT_5
#spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto = update
